### ISSUE TITLE
Spaces are ignored

### ISSUE THREAD

**Issue by vaderus** [natrys/keepassxc-dmenu#4]
Spaces are ignored when printing with xdotool

**Comment by natrys** [comment]
Thanks for the report, can confirm.

I was aware that quotes wouldn't work due to xdotool's script mode parsing problem, but space also not working is unfortunate. I didn't realise it because my generator doesn't include spaces.

Anyway, I thought I should use script mode out of principle because of the remote chance that system has some sort of program/syscall monitoring, which would log password if its provided as parameter.

Thankfully, now that I looked deeper, there seems to be `--file` option for xdotool which could also be specified for stdin. It's not full script mode, but reads just the input from stdin, and also doesn't have any of the parsing problems apparently.

I have pushed the fix in latest commit, would appreciate if you could test.

**Comment by vaderus** [comment]
Confirmed, spaces are working now. 
Thank you!
